//
//  KSUnityConnector.h
//  Unity-iPhone
//
//  Created by Toru Inoue on 2012/12/02.
//
//




#import <Foundation/Foundation.h>

#define KS_UNITYCONNECTOR  (@"KS_UNITYCONNECTOR")


typedef enum{
	KS_UNITYCONNECTOR_EXEC_INITIALIZE,
	KS_UNITYCONNECTOR_EXEC_DIDBECOMEACTIVE,
	KS_UNITYCONNECTOR_EXEC_WILLRESIGNACTIVE,
	KS_UNITYCONNECTOR_EXEC_WILLTERMINATE,
	KS_UNITYCONNECTOR_EXEC_DIDRECEIVEMEMORYWARNING,
	KS_UNITYCONNECTOR_EXEC_DIDREGISTERFORREMOTENOTIFICATIONSWITHDEVICETOKEN,
	KS_UNITYCONNECTOR_EXEC_DIDFAILTOREGISTERFORREMOTENOTIFICATIONWITHERROR,
	KS_UNITYCONNECTOR_EXEC_DIDRECEIVEREMOTENOTIFICATION,
	KS_UNITYCONNECTOR_EXEC_DIDRECEIVELOCALNOTIFICATION,
	KS_UNITYCONNECTOR_EXEC_DIDENTERBACKGROUND,
	KS_UNITYCONNECTOR_EXEC_WILLENTERFOREGROUND,
	KS_UNITYCONNECTOR_EXEC_SUPPORTEDINTERFACEORIENTATIONFORWINDOW,
	KS_UNITYCONNECTOR_EXEC_VIEWCANBEAPPEND,
	
	KS_UNITYCONNECTOR_EXEC_ADD_VIEW,
	KS_UNITYCONNECTOR_EXEC_REMOVE_ALL_VIEW
	
} UnityConnector;


#define KS_UNITYCONNECTOR_DEFINE_OBSERVE_WHENUNITYBOOTED	(@"NSUserDefaultsDidChangeNotification")

/*
 other candidates:
 
 NSUserDefaultsDidChangeNotification
 WebPreferencesChangedInternalNotification
 WAKWindowScreenScaleDidChangeNotification	//iOS 6 over only
 */


@interface KSUnityConnector : NSObject {
	__weak UIWindow * m_unityWindow;
}
- (id)initKSUnityConnectorWithMasterName:(NSString * )masterName;
@end
