//
//  KSUnityConnector.h
//  Unity-iPhone
//
//  Created by Toru Inoue on 2012/12/02.
//
//

#import <Foundation/Foundation.h>
#import "MessengerSystem.h"

#define KS_UNITYCONNECTOR  (@"KS_UNITYCONNECTOR")

#define KS_UNITYCONNECTOR_EXEC_INITIALIZE  (@"KS_UNITYCONNECTOR_EXEC_INITIALIZE")
#define KS_UNITYCONNECTOR_EXEC_DIDBECOMEACTIVE (@"KS_UNITYCONNECTOR_EXEC_DIDBECOMEACTIVE")
#define KS_UNITYCONNECTOR_EXEC_WILLRESIGNACTIVE    (@"KS_UNITYCONNECTOR_EXEC_WILLRESIGNACTIVE")
#define KS_UNITYCONNECTOR_EXEC_WILLTERMINATE    (@"KS_UNITYCONNECTOR_EXEC_WILLTERMINATE")
#define KS_UNITYCONNECTOR_EXEC_DIDRECEIVEMEMORYWARNING (@"KS_UNITYCONNECTOR_EXEC_DIDRECEIVEMEMORYWARNING")

#define KS_UNITYCONNECTOR_EXEC_DIDREGISTERFORREMOTENOTIFICATIONSWITHDEVICETOKEN    (@"KS_UNITYCONNECTOR_EXEC_DIDREGISTERFORREMOTENOTIFICATIONSWITHDEVICETOKEN")
#define KS_UNITYCONNECTOR_EXEC_DIDFAILTOREGISTERFORREMOTENOTIFICATIONWITHERROR (@"KS_UNITYCONNECTOR_EXEC_DIDFAILTOREGISTERFORREMOTENOTIFICATIONWITHERROR")
#define KS_UNITYCONNECTOR_EXEC_DIDRECEIVEREMOTENOTIFICATION    (@"KS_UNITYCONNECTOR_EXEC_DIDRECEIVEREMOTENOTIFICATION")
#define KS_UNITYCONNECTOR_EXEC_DIDRECEIVELOCALNOTIFICATION (@"KS_UNITYCONNECTOR_EXEC_DIDRECEIVELOCALNOTIFICATION")

#define KS_UNITYCONNECTOR_EXEC_DIDENTERBACKGROUND  (@"KS_UNITYCONNECTOR_EXEC_DIDENTERBACKGROUND")
#define KS_UNITYCONNECTOR_EXEC_WILLENTERFOREGROUND (@"KS_UNITYCONNECTOR_EXEC_WILLENTERFOREGROUND")

#define KS_UNITYCONNECTOR_EXEC_SUPPORTEDINTERFACEORIENTATIONFORWINDOW   (@"KS_UNITYCONNECTOR_EXEC_SUPPORTEDINTERFACEORIENTATIONFORWINDOW")
#define KS_UNITYCONNECTOR_EXEC_VIEWCANBEAPPEND	(@"KS_UNITYCONNECTOR_EXEC_VIEWCANBEAPPEND")

#define KS_UNITYCONNECTOR_EXEC_ADD_VIEW	(@"KS_UNITYCONNECTOR_EXEC_ADD_VIEW")
#define KS_UNITYCONNECTOR_EXEC_REMOVE_ALL_VIEW		(@"KS_UNITYCONNECTOR_EXEC_REMOVE_ALL_VIEW")



#define KS_UNITYCONNECTOR_DEFINE_OBSERVE_WHENUNITYBOOTED	(@"NSUserDefaultsDidChangeNotification")
/*
 other candidates:
 
 NSUserDefaultsDidChangeNotification
 WebPreferencesChangedInternalNotification
 WAKWindowScreenScaleDidChangeNotification	//iOS 6 over only
 */


@interface KSUnityConnector : NSObject {
    MessengerSystem * messenger;
	
	UIWindow * m_unityWindow;
}
- (id)initKSUnityConnectorWithMasterName:(NSString * )masterName;
@end
