//
//  KSUnityBooter.h
//  Unity-iPhone
//
//  Created by Toru Inoue on 2012/12/02.
//
//

#import <Foundation/Foundation.h>
#import "MessengerSystem.h"

#define KS_UNITYBOOTER  (@"KS_UNITYBOOTER")

#define KS_UNITYBOOTER_EXEC_INITIALIZE  (@"KS_UNITYBOOTER_EXEC_INITIALIZE")
#define KS_UNITYBOOTER_EXEC_DIDBECOMEACTIVE (@"KS_UNITYBOOTER_EXEC_DIDBECOMEACTIVE")
#define KS_UNITYBOOTER_EXEC_WILLRESIGNACTIVE    (@"KS_UNITYBOOTER_EXEC_WILLRESIGNACTIVE")
#define KS_UNITYBOOTER_EXEC_WILLTERMINATE    (@"KS_UNITYBOOTER_EXEC_WILLTERMINATE")
#define KS_UNITYBOOTER_EXEC_DIDRECEIVEMEMORYWARNING (@"KS_UNITYBOOTER_EXEC_DIDRECEIVEMEMORYWARNING")

#define KS_UNITYBOOTER_EXEC_DIDREGISTERFORREMOTENOTIFICATIONSWITHDEVICETOKEN    (@"KS_UNITYBOOTER_EXEC_DIDREGISTERFORREMOTENOTIFICATIONSWITHDEVICETOKEN")
#define KS_UNITYBOOTER_EXEC_DIDFAILTOREGISTERFORREMOTENOTIFICATIONWITHERROR (@"KS_UNITYBOOTER_EXEC_DIDFAILTOREGISTERFORREMOTENOTIFICATIONWITHERROR")
#define KS_UNITYBOOTER_EXEC_DIDRECEIVEREMOTENOTIFICATION    (@"KS_UNITYBOOTER_EXEC_DIDRECEIVEREMOTENOTIFICATION")
#define KS_UNITYBOOTER_EXEC_DIDRECEIVELOCALNOTIFICATION (@"KS_UNITYBOOTER_EXEC_DIDRECEIVELOCALNOTIFICATION")

#define KS_UNITYBOOTER_EXEC_DIDENTERBACKGROUND  (@"KS_UNITYBOOTER_EXEC_DIDENTERBACKGROUND")
#define KS_UNITYBOOTER_EXEC_WILLENTERFOREGROUND (@"KS_UNITYBOOTER_EXEC_WILLENTERFOREGROUND")

#define KS_UNITYBOOTER_EXEC_SUPPORTEDINTERFACEORIENTATIONFORWINDOW   (@"KS_UNITYBOOTER_EXEC_SUPPORTEDINTERFACEORIENTATIONFORWINDOW")
#define KS_UNITYBOOTER_EXEC_VIEWCANBEAPPEND	(@"KS_UNITYBOOTER_EXEC_VIEWCANBEAPPEND")

#define KS_UNITYBOOTER_EXEC_ADD_VIEW	(@"KS_UNITYBOOTER_EXEC_ADD_VIEW")
#define KS_UNITYBOOTER_EXEC_REMOVE_ALL_VIEW		(@"KS_UNITYBOOTER_EXEC_REMOVE_ALL_VIEW")



#define KS_UNITYBOOTER_DEFINE_OBSERVE_WHENUNITYBOOTED	(@"NSUserDefaultsDidChangeNotification")
/*
 other candidates:
 
 NSUserDefaultsDidChangeNotification
 WebPreferencesChangedInternalNotification
 WAKWindowScreenScaleDidChangeNotification	//iOS 6 over only
 */


@interface KSUnityBooter : NSObject {
    MessengerSystem * messenger;
	
	UIWindow * m_unityWindow;
}
- (id)initKSUnityBooterWithMasterName:(NSString * )masterName;
@end
