//
//  KSUnityBooter.h
//  Unity-iPhone
//
//  Created by Toru Inoue on 2012/12/02.
//
//

#import <Foundation/Foundation.h>
#import "MessengerSystem.h"

#define KS_UNITYBOOTER  (@"KS_UNITYBOOTER")

#define KS_UNITYBOOTER_EXEC_INITIALIZE  (@"KS_UNITYBOOTER_EXEC_INITIALIZE")
#define KS_UNITYBOOTER_EXEC_DIDBECOMEACTIVE (@"KS_UNITYBOOTER_EXEC_DIDBECOMEACTIVE")
#define KS_UNITYBOOTER_EXEC_WILLRESIGNACTIVE    (@"KS_UNITYBOOTER_EXEC_WILLRESIGNACTIVE")
#define KS_UNITYBOOTER_EXEC_APPLICATIONWILLTERMINATE    (@"KS_UNITYBOOTER_EXEC_APPLICATIONWILLTERMINATE")
#define KS_UNITYBOOTER_EXEC_DIDRECEIVEMEMORYWARNING (@"KS_UNITYBOOTER_EXEC_DIDRECEIVEMEMORYWARNING")

#define KS_UNITYBOOTER_EXEC_DIDREGISTERFORREMOTENOTIFICATIONSWITHDEVICETOKEN    (@"KS_UNITYBOOTER_EXEC_DIDREGISTERFORREMOTENOTIFICATIONSWITHDEVICETOKEN")
#define KS_UNITYBOOTER_EXEC_DIDFAILTOREGISTERFORREMOTENOTIFICATIONWITHERROR (@"KS_UNITYBOOTER_EXEC_DIDFAILTOREGISTERFORREMOTENOTIFICATIONWITHERROR")
#define KS_UNITYBOOTER_EXEC_DIDRECEIVEREMOTENOTIFICATION    (@"KS_UNITYBOOTER_EXEC_DIDRECEIVEREMOTENOTIFICATION")
#define KS_UNITYBOOTER_EXEC_DIDRECEIVELOCALNOTIFICATION (@"KS_UNITYBOOTER_EXEC_DIDRECEIVELOCALNOTIFICATION")

#define KS_UNITYBOOTER_EXEC_DIDENTERBACKGROUND  (@"KS_UNITYBOOTER_EXEC_DIDENTERBACKGROUND")
#define KS_UNITYBOOTER_EXEC_WILLENTERFOREGROUND (@"KS_UNITYBOOTER_EXEC_WILLENTERFOREGROUND")

#define KS_UNITYBOOTER_SUPPORTEDINTERFACEORIENTATIONFORWINDOW   (@"KS_UNITYBOOTER_SUPPORTEDINTERFACEORIENTATIONFORWINDOW")



@interface KSUnityBooter : NSObject {
    MessengerSystem * messenger;
}
- (id)initKSUnityBooterWithMasterName:(NSString * )masterName;
@end
